# Generated by Django 3.2.4 on 2021-06-27 19:51

import careers.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_career', models.FileField(blank=True, null=True, upload_to='background/career/', validators=[careers.validators.validate_image_extension])),
                ('title', models.CharField(default='', max_length=300)),
                ('description', ckeditor.fields.RichTextField()),
                ('contract_duration', models.CharField(default='', max_length=300)),
                ('job_type', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1)),
                ('job_shift', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1)),
                ('location', models.CharField(default='', max_length=300)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('minimum_education', models.CharField(default='', max_length=300)),
                ('minimum_experience', models.CharField(default='', max_length=300)),
                ('required_travel', models.CharField(default='', max_length=150)),
                ('no_of_jobs', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField()),
                ('image_footer_logo_career_detail', models.FileField(blank=True, null=True, upload_to='background/career/', validators=[careers.validators.validate_image_extension])),
                ('image_header_logo_sticky_career_detail', models.FileField(blank=True, null=True, upload_to='background/career/', validators=[careers.validators.validate_image_extension])),
            ],
        ),
    ]
