# Generated by Django 3.0.6 on 2021-06-30 01:42

import careers.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('contract_duration', models.CharField(default='', max_length=300)),
                ('governorate', models.CharField(default='', max_length=300)),
                ('job_type', models.CharField(choices=[
                 ('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1)),
                ('job_shift', models.CharField(choices=[
                 ('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1)),
                ('location', models.CharField(default='', max_length=300, null=True)),
                ('posted', models.DateField(default=datetime.date.today, null=True)),
                ('minimum_education', models.CharField(default='', max_length=300)),
                ('minimum_experience', models.CharField(
                    default='', max_length=300)),
                ('required_travel', models.CharField(default='', max_length=150)),
                ('no_of_jobs', models.PositiveIntegerField(default=1)),
                ('puplished', models.DateField(
                    default=datetime.date.today, null=True)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
