# Generated by Django 3.2.4 on 2021-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdetail',
            name='description',
            field=models.TextField(),
        ),
    ]
