# Generated by Django 3.0.6 on 2021-08-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdetail',
            name='qualifications_and_preferred_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_and_responsibilities',
            field=models.TextField(null=True),
        ),
    ]
