# Generated by Django 3.0.6 on 2021-06-30 02:53

import careers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdetail',
            name='image_career_details',
            field=models.FileField(blank=True, null=True, upload_to='background/career_details/', validators=[careers.validators.validate_image_extension]),
        ),
    ]
