# Generated by Django 3.0.6 on 2021-06-30 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careerdetail_image_career_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdetail',
            name='posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='careerdetail',
            name='puplished',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
