# Generated by Django 3.0.6 on 2021-08-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20210813_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerdetail',
            name='role_and_responsibilities',
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerdetail',
            name='role_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
