# Generated by Django 3.0.6 on 2021-06-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20210630_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerdetail',
            name='slug',
        ),
    ]
