# Generated by Django 3.0.6 on 2021-07-01 10:31

import careers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_remove_careerdetail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_career_list', models.FileField(blank=True, null=True, upload_to='background/career_list/', validators=[careers.validators.validate_image_extension])),
                ('image_header_logo_sticky_career_list', models.FileField(blank=True, null=True, upload_to='background/career_list/', validators=[careers.validators.validate_image_extension])),
                ('image_footer_logo_career_list', models.FileField(blank=True, null=True, upload_to='background/career_list/', validators=[careers.validators.validate_image_extension])),
            ],
        ),
    ]
