# Generated by Django 3.0.6 on 2021-07-01 17:23

import careers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_careerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDetatilImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_header_logo_sticky_career_detail_image', models.FileField(blank=True, null=True, upload_to='background/career_detail_image /', validators=[careers.validators.validate_image_extension])),
                ('image_footer_logo_career_detail_image', models.FileField(blank=True, null=True, upload_to='background/career_detail_image /', validators=[careers.validators.validate_image_extension])),
            ],
        ),
    ]
