# Generated by Django 3.0.6 on 2021-07-01 17:29

import careers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_careerdetatilimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdetatilimage',
            name='image_footer_logo_career_detail_image',
            field=models.FileField(blank=True, null=True, upload_to='background/career_detail_image/', validators=[careers.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='careerdetatilimage',
            name='image_header_logo_sticky_career_detail_image',
            field=models.FileField(blank=True, null=True, upload_to='background/career_detail_image/', validators=[careers.validators.validate_image_extension]),
        ),
    ]
