# Generated by Django 3.0.6 on 2021-07-11 04:51

import django.core.validators
from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_middle_about', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_about', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.             Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('region', models.CharField(choices=[('Baghdad', 'Baghdad'), ('Mousl', 'Mousl'), ('Erbil', 'Erbil'), ('Anbar', 'Anbar'), ('Babylon', 'Babylon'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Diyala', 'Diyala'), ('Dohuk', 'Dohuk'), ('Karbala', 'Karbala'), ('KirKuk', 'KirKuk'), ('Maysan', 'Maysan'), ('Najaf', 'Najaf'), ('Qaisiyah', 'Qaisiyah'), ('Salahaddin', 'Salahaddin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=12)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('english', models.CharField(blank=True, default='English', max_length=7, null=True)),
                ('kurdish', models.CharField(blank=True, default='Kurdish', max_length=7, null=True)),
                ('arabic', models.CharField(blank=True, default='Arabic', max_length=6, null=True)),
                ('cover_letter', models.TextField()),
                ('upload_cv', models.FileField(upload_to='uploadcv/', validators=[jobs.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.CharField(default='', max_length=300)),
                ('phone_contact', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_donate', models.FileField(blank=True, null=True, upload_to='background/donate/', validators=[jobs.validators.validate_image_extension])),
                ('facebook_link', models.CharField(default='', max_length=300)),
                ('twitter_link', models.CharField(default='', max_length=300)),
                ('instagram_link', models.CharField(default='', max_length=300)),
                ('location_donate', models.CharField(default='', max_length=300)),
                ('email_donate', models.CharField(default='', max_length=300)),
                ('phone_donate', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GetInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_careers_getinvolved', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_careers_getinvolved', models.CharField(default='', max_length=300)),
                ('image_joinus_getinvolved', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_joinus_getinvolved', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_about_index', models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension])),
                ('text_about_index', models.CharField(default='', max_length=300)),
                ('text_what_we_are_doing_index', models.CharField(default='', max_length=300)),
                ('image_story_index', models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension])),
                ('text_story_index', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image_index', models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension])),
                ('slide_title_index', models.CharField(default='', max_length=300)),
                ('slide_subtitle_index', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vission_Mission_Value_desc1', models.CharField(default='', max_length=300)),
                ('Vission_Mission_Value_desc2', models.CharField(default='', max_length=300)),
                ('vission_text', models.CharField(default='', max_length=300)),
                ('mission_text', models.CharField(default='', max_length=300)),
                ('value_text', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_volunteer', models.FileField(blank=True, null=True, upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeAreDoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_what_we_are_doing', models.FileField(blank=True, null=True, upload_to='background/whatwe/', validators=[jobs.validators.validate_image_extension])),
                ('image_header_logo_sticky_what_we_are_doing', models.FileField(blank=True, null=True, upload_to='background/whatwe/', validators=[jobs.validators.validate_image_extension])),
                ('image_footer_logo_what_we_are_doing', models.FileField(blank=True, null=True, upload_to='background/whatwe/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeAreDoingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhatWeAreDoing_details_image_gallery', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhatWeAreDoing_details_image1', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhatWeAreDoing_details_image2', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhatWeAreDoing_details_image3', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhatWeAreDoing_details_name', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc1', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc2', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc3', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc4', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc5', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc6', models.CharField(default='', max_length=300)),
                ('WhatWeAreDoing_details_desc7', models.CharField(default='', max_length=300)),
                ('image_bg_what_we_are_doing_details', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_right', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_middle', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_left', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_one', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_two', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_three', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_four', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_five', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_sex', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_footer_logo_what_we_are_doing_details', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_header_logo_sticky_what_we_are_doing_details', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhoWeAre_image1', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhoWeAre_image2', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhoWeAre_image3', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension])),
                ('WhoWeAre_desc1', models.CharField(default='', max_length=300)),
                ('WhoWeAre_desc2', models.CharField(default='', max_length=300)),
                ('WhoWeAre_desc3', models.CharField(default='', max_length=300)),
                ('WhoWeAre_desc4', models.CharField(default='', max_length=300)),
                ('WhoWeAre_desc5', models.CharField(default='', max_length=300)),
                ('WhoWeAre_desc6', models.CharField(default='', max_length=300)),
                ('WhoWeAre_desc7', models.CharField(default='', max_length=300)),
                ('image_bg_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
