# Generated by Django 3.0.6 on 2021-07-03 20:43

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMissionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vission_Mission_Value_desc1', models.CharField(default='', max_length=300)),
                ('Vission_Mission_Value_desc2', models.CharField(default='', max_length=300)),
                ('vission_text', models.CharField(default='', max_length=300)),
                ('mission_text', models.CharField(default='', max_length=300)),
                ('value_text', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='slide_image_index',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='index',
            name='slide_subtitle_index',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='index',
            name='slide_title_index',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc6',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_desc7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_image1',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_image2',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_image3',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_image_gallery',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetails',
            name='WhatWeAreDoing_details_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc6',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_desc7',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_image1',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_image2',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='WhoWeAre_image3',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
