# Generated by Django 3.2.3 on 2021-06-17 23:05

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='upload_cv',
            field=models.FileField(upload_to='', validators=[jobs.validators.validate_file_extension]),
        ),
    ]
