# Generated by Django 3.0.6 on 2021-07-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210703_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image_bg_index_one',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_bg_index_three',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_bg_index_two',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_footer_logo',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_header_logo_sticky',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_index_stories_four',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_index_stories_one',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_index_stories_three',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_index_stories_two',
        ),
        migrations.RemoveField(
            model_name='index',
            name='index_animals',
        ),
    ]
