# Generated by Django 3.2.3 on 2021-06-17 23:06

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_upload_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='upload_cv',
            field=models.FileField(upload_to='media/', validators=[jobs.validators.validate_file_extension]),
        ),
    ]
