# Generated by Django 3.0.6 on 2021-07-13 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210711_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.             Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
