# Generated by Django 3.0.6 on 2021-07-07 05:05

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210706_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='upload_cv_two',
            field=models.FileField(blank=True, null=True, upload_to='uploadcv/', validators=[jobs.validators.validate_file_extension]),
        ),
    ]
