# Generated by Django 3.0.6 on 2021-08-13 21:35

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210713_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image_story_index',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='index',
            name='text_story_index',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='index',
            name='whatDoDetail_text',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_icon_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
