# Generated by Django 3.0.6 on 2021-07-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_upload_cv_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='upload_cv_two',
        ),
    ]
