# Generated by Django 3.0.6 on 2021-08-28 06:34

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210825_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_middle_about',
            field=models.FileField(blank=True, default='', upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_about',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='email_donate',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='donate',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='donate',
            name='image_bg_donate',
            field=models.FileField(blank=True, default='', upload_to='background/donate/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='donate',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='donate',
            name='location_donate',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='donate',
            name='phone_donate',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='donate',
            name='twitter_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='image_careers_getinvolved',
            field=models.FileField(blank=True, default='', upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='image_joinus_getinvolved',
            field=models.FileField(blank=True, default='', upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='text_careers_getinvolved',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='getinvolved',
            name='text_joinus_getinvolved',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_about_index',
            field=models.FileField(blank=True, default='', upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_story_index',
            field=models.FileField(blank=True, default='', upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='text_about_index',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='index',
            name='text_story_index',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='index',
            name='whatDoDetail_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide_image_index',
            field=models.FileField(blank=True, default='', upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide_subtitle_index',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide_title_index',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='mission_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='value_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='vission_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_bg_volunteer',
            field=models.FileField(blank=True, default='', upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc3',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc5',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc6',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_desc7',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_icon_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image1',
            field=models.FileField(blank=True, default='', upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image2',
            field=models.FileField(blank=True, default='', upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image3',
            field=models.FileField(blank=True, default='', upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_image_gallery',
            field=models.FileField(blank=True, default='', upload_to='background/WhatWeAreDoingDetails/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoingdetail',
            name='whatDoDetail_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc3',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc5',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc6',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_desc7',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_image1',
            field=models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_image2',
            field=models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='WhoWeAre_image3',
            field=models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='image_bg_who_we_are',
            field=models.FileField(blank=True, default='', upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
