# Generated by Django 3.0.6 on 2021-08-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210828_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(help_text='full_name', max_length=200),
        ),
    ]
