# Generated by Django 3.2.3 on 2021-06-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_application_upload_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
