# Generated by Django 3.0.6 on 2021-08-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20210829_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='text_about_index_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
