# Generated by Django 3.0.6 on 2021-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_index_text_about_index_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='whatDoDetail_text_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
