# Generated by Django 3.2.4 on 2021-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_remove_application_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_language', models.CharField(choices=[('1', 'English'), ('2', 'Arabic'), ('3', 'Kurdish')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='application',
            name='language',
        ),
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.ManyToManyField(to='jobs.LanguageChoices'),
        ),
    ]
