# Generated by Django 3.2.4 on 2021-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20210621_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='language',
        ),
        migrations.AddField(
            model_name='application',
            name='arabic',
            field=models.CharField(blank=True, choices=[('Arabic', 'Arabic')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='english',
            field=models.CharField(blank=True, choices=[('English', 'English')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='kurdish',
            field=models.CharField(blank=True, choices=[('Kurdish', 'Kurdish')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.CharField(choices=[('Baghdad', 'Baghdad'), ('Mousl', 'Mousl'), ('Erbil', 'Erbil'), ('Anbar', 'Anbar'), ('Babylon', 'Babylon'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Diyala', 'Diyala'), ('Dohuk', 'Dohuk'), ('Karbala', 'Karbala'), ('KirKuk', 'KirKuk'), ('Maysan', 'Maysan'), ('Najaf', 'Najaf'), ('Qaisiyah', 'Qaisiyah'), ('Salahaddin', 'Salahaddin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=12),
        ),
        migrations.DeleteModel(
            name='LanguageChoices',
        ),
    ]
