# Generated by Django 3.2.4 on 2021-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20210621_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='arabic',
            field=models.BooleanField(choices=[('Arabic', 'Arabic')], default=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='application',
            name='english',
            field=models.BooleanField(choices=[('English', 'English')], default=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='application',
            name='kurdish',
            field=models.BooleanField(choices=[('Kurdish', 'Kurdish')], default=False, max_length=7),
        ),
    ]
