# Generated by Django 3.2.4 on 2021-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20210621_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='arabic',
            field=models.BooleanField(choices=[('Arabic', 'Arabic')], default=False, max_length=6),
        ),
    ]
