# Generated by Django 3.2.4 on 2021-06-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20210622_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='arabic',
            field=models.CharField(choices=[('Arabic', 'Arabic')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='english',
            field=models.CharField(choices=[('English', 'English')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='kurdish',
            field=models.CharField(choices=[('Kurdish', 'Kurdish')], max_length=7, null=True),
        ),
    ]
