# Generated by Django 3.2.4 on 2021-06-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20210622_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='arabic',
            field=models.CharField(blank=True, default='Arabic', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='english',
            field=models.CharField(blank=True, default='English', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='kurdish',
            field=models.CharField(blank=True, default='Kurdish', max_length=7, null=True),
        ),
    ]
