# Generated by Django 3.2.4 on 2021-06-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20210622_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='arabic',
        ),
        migrations.RemoveField(
            model_name='application',
            name='english',
        ),
        migrations.RemoveField(
            model_name='application',
            name='kurdish',
        ),
    ]
