# Generated by Django 3.2.4 on 2021-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_whatwearedoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwearedoing',
            name='image_layer_bg',
            field=models.ImageField(height_field=1920, upload_to='background/', width_field=350),
        ),
    ]
