# Generated by Django 3.2.4 on 2021-06-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_alter_whatwearedoing_image_layer_bg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatwearedoing',
            old_name='image_layer_bg',
            new_name='imagelayerbg',
        ),
    ]
