# Generated by Django 3.2.4 on 2021-06-22 13:14

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_rename_image_layer_bg_whatwearedoing_imagelayerbg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwearedoing',
            name='imagelayerbg',
            field=models.FileField(upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
