# Generated by Django 3.2.4 on 2021-06-22 13:58

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_alter_whatwearedoing_imagelayerbg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_volunteer', models.FileField(upload_to='background/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.RenameField(
            model_name='whatwearedoing',
            old_name='imagelayerbg',
            new_name='image_bg_what_we_are_doing',
        ),
    ]
