# Generated by Django 3.2.4 on 2021-06-22 14:20

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_auto_20210622_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_index', models.FileField(upload_to='background/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
