# Generated by Django 3.2.4 on 2021-06-22 14:38

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='image_bg_index',
        ),
        migrations.AddField(
            model_name='index',
            name='image_bg_index_one',
            field=models.FileField(null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='index',
            name='image_bg_index_three',
            field=models.FileField(null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='index',
            name='image_bg_index_two',
            field=models.FileField(null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
