# Generated by Django 3.2.4 on 2021-06-22 20:04

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_auto_20210622_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='index_animals',
            field=models.FileField(null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
