# Generated by Django 3.2.4 on 2021-06-22 21:01

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_index_index_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image_index_stories_one',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_bg_index_one',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_bg_index_three',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_bg_index_two',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_animals',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
