# Generated by Django 3.2.4 on 2021-06-22 21:35

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_auto_20210622_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='image_footer_logo',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='index',
            name='image_footer_logo_sticky',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
