# Generated by Django 3.2.4 on 2021-06-22 22:28

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_auto_20210622_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='image_footer_logo_sticky',
            new_name='image_header_logo_sticky',
        ),
        migrations.AddField(
            model_name='whatwearedoing',
            name='image_footer_logo_what_we_are_doing',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='whatwearedoing',
            name='image_header_logo_sticky_what_we_are_doing',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_bg_volunteer',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoing',
            name='image_bg_what_we_are_doing',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
