# Generated by Django 3.2.4 on 2021-06-22 22:34

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_auto_20210623_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='image_footer_logo_volunteer',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image_header_logo_sticky_volunteer',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
