# Generated by Django 3.2.4 on 2021-06-22 22:56

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_auto_20210623_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_donate', models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension])),
                ('image_header_logo_sticky_donate', models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension])),
                ('image_footer_logo_donate', models.FileField(blank=True, null=True, upload_to='background/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
