# Generated by Django 3.2.4 on 2021-06-22 23:17

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='image_bg_donate',
            field=models.FileField(blank=True, null=True, upload_to='background/donate/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='donate',
            name='image_footer_logo_donate',
            field=models.FileField(blank=True, null=True, upload_to='background/donate/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='donate',
            name='image_header_logo_sticky_donate',
            field=models.FileField(blank=True, null=True, upload_to='background/donate/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_bg_index_one',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_bg_index_three',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_bg_index_two',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_footer_logo',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_header_logo_sticky',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_index_stories_four',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_index_stories_one',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_index_stories_three',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='image_index_stories_two',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='index',
            name='index_animals',
            field=models.FileField(blank=True, null=True, upload_to='background/index/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_bg_volunteer',
            field=models.FileField(blank=True, null=True, upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_footer_logo_volunteer',
            field=models.FileField(blank=True, null=True, upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image_header_logo_sticky_volunteer',
            field=models.FileField(blank=True, null=True, upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoing',
            name='image_bg_what_we_are_doing',
            field=models.FileField(blank=True, null=True, upload_to='background/whatwe/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoing',
            name='image_footer_logo_what_we_are_doing',
            field=models.FileField(blank=True, null=True, upload_to='background/whatwe/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='whatwearedoing',
            name='image_header_logo_sticky_what_we_are_doing',
            field=models.FileField(blank=True, null=True, upload_to='background/whatwe/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
