# Generated by Django 3.2.4 on 2021-06-23 00:55

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_auto_20210623_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeAreDoingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_what_we_are_doing_details', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_right', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_middle', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_left', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_one', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_two', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_three', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_four', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_five', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_what_we_are_doing_details_sex', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_footer_logo_what_we_are_doing_details', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
                ('image_header_logo_sticky_what_we_are_doing_details', models.FileField(blank=True, null=True, upload_to='background/WhatWeDetails/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
