# Generated by Django 3.2.4 on 2021-06-23 12:14

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_whatwearedoingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_about', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_middle_about', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_header_logo_sticky_about', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_footer_logo_about', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
