# Generated by Django 3.2.4 on 2021-06-23 14:20

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_getinvolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_left_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_middle_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_right_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_header_logo_sticky_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('image_footer_logo_who_we_are', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
