# Generated by Django 3.1 on 2021-05-02 22:06

import activities.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.             Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('region', models.CharField(choices=[('1', 'Baghdad'), ('2', 'Mousl'), ('3', 'Erbil'), ('4', 'Anbar'), ('5', 'Babylon'), ('6', 'Basra'), ('7', 'Dhi Qar'), ('8', 'Diyala'), ('9', 'Dohuk'), ('10', 'Karbala'), ('11', 'KirKuk'), ('12', 'Maysan'), ('13', 'Najaf'), ('14', 'Qaisiyah'), ('15', 'Salahaddin'), ('16', 'Sulaymaniyah'), ('17', 'Wasit')], max_length=2)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male')], max_length=1)),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'Arabic'), ('3', 'Kurdish')], max_length=1)),
                ('cover_letter', models.TextField()),
                ('upload_cv', models.FileField(upload_to='uploaded_files/', validators=[activities.validators.validate_file_extension])),
            ],
        ),
    ]
