# Generated by Django 3.2.4 on 2021-06-27 04:51

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_blogs', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_right', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_middle', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_left', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_one', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_two', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_three', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_four', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_five', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_sex', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_seven', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_blogs_eight', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_footer_logo_blogs', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_header_logo_sticky_blogs', models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='StoriesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_stories_detail', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_right', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_middle', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_left', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_one', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_two', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_three', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_four', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_five', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_detail_sex', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_footer_logo_stories_detail', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
                ('image_header_logo_sticky_stories_detail', models.FileField(blank=True, null=True, upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_story', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_one', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_two', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_three', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_four', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_five', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_sex', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_seven', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_story_eight', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_footer_logo_story', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
                ('image_header_logo_sticky_story', models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='StoryAndBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_stories_and_blogs', models.FileField(blank=True, null=True, upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_and_blogs_left', models.FileField(blank=True, null=True, upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_stories_and_blogs_middle', models.FileField(blank=True, null=True, upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_footer_logo_stories_and_blogs', models.FileField(blank=True, null=True, upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
                ('image_header_logo_sticky_stories_and_blogs', models.FileField(blank=True, null=True, upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_team', models.FileField(blank=True, null=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
                ('image_team_right', models.FileField(blank=True, null=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
                ('image_team_middle', models.FileField(blank=True, null=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
                ('image_team_left', models.FileField(blank=True, null=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
                ('image_footer_logo_team', models.FileField(blank=True, null=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
                ('image_header_logo_sticky_team', models.FileField(blank=True, null=True, upload_to='background/team/', validators=[blogs.validators.validate_image_extension])),
            ],
        ),
    ]
