# Generated by Django 3.0.6 on 2021-07-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoriesDetail',
            new_name='StoryDetail',
        ),
        migrations.DeleteModel(
            name='StoryList',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_date',
            new_name='story_date',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc1',
            new_name='story_desc1',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc2',
            new_name='story_desc2',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc3',
            new_name='story_desc3',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc4',
            new_name='story_desc4',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc5',
            new_name='story_desc5',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc6',
            new_name='story_desc6',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_desc7',
            new_name='story_desc7',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_image_one',
            new_name='story_image_one',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_image_three',
            new_name='story_image_three',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_image_two',
            new_name='story_image_two',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_location',
            new_name='story_location',
        ),
        migrations.RenameField(
            model_name='storydetail',
            old_name='stories_details_name',
            new_name='story_name',
        ),
    ]
