# Generated by Django 3.2.4 on 2021-06-27 01:43

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_bg_blogs',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_eight',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_five',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_four',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_left',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_middle',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_one',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_right',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_seven',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_sex',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_three',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_blogs_two',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_footer_logo_blogs',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_header_logo_sticky_blogs',
            field=models.FileField(blank=True, null=True, upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
