# Generated by Django 3.0.6 on 2021-08-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210711_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storydetail',
            options={'ordering': ['-story_date']},
        ),
    ]
