# Generated by Django 3.0.6 on 2021-07-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210708_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='StoryList',
        ),
    ]
