# Generated by Django 3.2.4 on 2021-06-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_storiesdetail_story_storyandblog_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_eight',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_five',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_four',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_left',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_one',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_seven',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_sex',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_three',
        ),
        migrations.RemoveField(
            model_name='storyandblog',
            name='image_stories_and_blogs_two',
        ),
    ]
