# Generated by Django 3.2.4 on 2021-06-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210627_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyandblog',
            old_name='image_stories_and_blogs_right',
            new_name='image_stories_and_blogs_left',
        ),
    ]
