# Generated by Django 3.2.4 on 2021-06-27 04:45

import blogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_image_stories_and_blogs_right_storyandblog_image_stories_and_blogs_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_bg_storydsd',
            field=models.FileField(blank=True, null=True, upload_to='background/story/', validators=[blogs.validators.validate_image_extension]),
        ),
    ]
