# Generated by Django 3.0.6 on 2021-08-28 06:34

import blogs.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210825_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogs_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogs_desc',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogs_image',
            field=models.FileField(blank=True, default='', upload_to='background/blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogs_location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storyandblog',
            name='image_bg_blogs',
            field=models.FileField(blank=True, default='', upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='storyandblog',
            name='image_bg_stories',
            field=models.FileField(blank=True, default='', upload_to='background/stories_and_blogs/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='storyandblog',
            name='text_bg_blogs',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storyandblog',
            name='text_bg_stories',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc1',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc2',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc3',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc5',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc6',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_desc7',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_image_one',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_image_three',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_image_two',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='storydetail',
            name='story_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='teams_desc',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='teams_image',
            field=models.FileField(blank=True, default='', upload_to='background/team/', validators=[blogs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='team',
            name='teams_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
