# Generated by Django 3.2.4 on 2021-06-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_story_image_bg_storydsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image_bg_storydsd',
        ),
    ]
